### ISSUE TITLE
[Example] OpenAI usage

### ISSUE THREAD

**Issue by michalsek** [software-mansion-labs/react-native-audio-api#222]
### Feature Request

- (Optional?) Add simple `decodeAudioData` method for reading raw PCM buffers and .wav files
- Add text-to-speech example using OpenAI

**Comment by DomoMKT** [comment]
you can find what you're looking for, including high-quality text-to-speech conversion with low latency, at [www.nemesyslabs.com](https://www.nemesyslabs.com).
