### ISSUE TITLE
decodeAudioDataSource is not defined

### ISSUE THREAD

**Issue by sgwanlee** [software-mansion-labs/react-native-audio-api#227]
Thank you for the great library.
I tried to run the AudioFile example on my project. However, I found no `decodeAudioDataSource` function in `0.2.0`.
When would it be included?

**Comment by michalsek** [comment]
Hey, thank you! :) 

Unfortunatelly `decodeAudioDataSource` is not yet available in `0.2.0`

It should be available in `0.3.0-rc1` which is available through `npm install react-native-audio-api@next`. But so far the implementation only supports iOS and web.

Once we will have android implemented and well-tested, we'll realease the full `0.3.0` :)

**Comment by sgwanlee** [comment]
Thank you for letting me know!

**Comment by maciejmakowski2003** [comment]
We have just released react-native-aduio-api `0.3.1`, which fully implements those functionality, so I am closing this issue :))
